version: "3.9"

services:
  shortner:
    image: zilioti.dev/shortner
    restart: always
    container_name: shortner
    ports:
      - "8000:8000"

networks:
  default:
    external: true
    name: portfolio_network
